### ISSUE TITLE
Error when opening Bookworm 32 bit

### ISSUE THREAD

**Issue by DraganRatkovich** [blindpandas/bookworm#117]
I have a few voices that can only be used when running Bookworm 32 bit so I decided to download and use it, but ran into a problem when running and @mush42 here is the log:

Traceback (most recent call last):
  File "bookworm\i18n\core.py", line 95, in setup_i18n
  File "locale.py", line 593, in getlocale
  File "locale.py", line 501, in _parse_localename
ValueError: unknown locale: en-GB

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bookworm\bookworm.py", line 51, in main
  File "bookworm\bootstrap.py", line 206, in run
  File "bookworm\bootstrap.py", line 196, in run
  File "bookworm\bootstrap.py", line 176, in init_app_and_run_main_loop
  File "bookworm\bootstrap.py", line 132, in setupSubsystems
  File "bookworm\i18n\core.py", line 97, in setup_i18n
  File "locale.py", line 610, in setlocale
locale.Error: unsupported locale setting.

### Bookworm version:
2022.1b1 portable X86

The 64-bit version works without problems.

**Comment by DraganRatkovich** [comment]
Hello,
@TheQuinbox Maybe you can fix this issue before the lead developer responds?

**Comment by DraganRatkovich** [comment]
Hello @mush42 Have you seen this issue?

**Comment by DraganRatkovich** [comment]
Hi @mush42 Have you seen this issue? I tried looking at the source code in the files referenced by the log, but since I don't understand Python much, I don't know what's going on.

**Comment by mush42** [comment]
I am working on fixing the Unicode errors right now.

**Comment by mush42** [comment]
Hello @DraganRatkovich 

This is a very strange behavior. Would you mind trying the latest build from appveyor again.

This issue has already been fixed in a previous version. Exception handlers already know about this exception, and handle it correctly.

Please try again with the latest build.
Also, please try the 64bit and 32bit variants in the same PC with the same locale.
Please provide the locale you're using.

Best
Musharraf

**Comment by DraganRatkovich** [comment]
Hi @mush42 I have already tested the builds downloaded from AppVeyor with the latest commits you pushed to Github yesterday, still have the same issue in Bookworm 32bit and my locale is US English but the log shows an en-gb error. I also tested on another Windows, where the locale is RU, but the en-gb error is still in the log and Bookworm does not start, again, I repeat, only the 32-bit version.

**Comment by DraganRatkovich** [comment]
@mush42 Forgot to say in previous comment, the bug can be easily reproduced with the release that is uploaded on the Github releases page still only in 32bit, so please let me know if anything can be fixed.

**Comment by DraganRatkovich** [comment]
@mush42 Tried using the Bookworm 32 bit installer a few minutes ago, installed but still the same error. en-gb, nothing more.

**Comment by mush42** [comment]
Hello @DraganRatkovich 

Not to belabor the point, here is a successful run log from the latest build of appveyor (based on yesterday's commit). Notice the architecture (x86) and the version (v2022.1b1).

INFO - bookworm.bookworm.bootstrap - 04/03/2022 23:01:51 - MainThread (14740):
Starting Bookworm.
INFO - bookworm.bookworm.bootstrap - 04/03/2022 23:01:51 - MainThread (14740):
Bookworm Version: 2022.1b1
INFO - bookworm.bookworm.bootstrap - 04/03/2022 23:01:51 - MainThread (14740):
Python version: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:01:48) [MSC v.1929 32 bit (Intel)]
INFO - bookworm.bookworm.bootstrap - 04/03/2022 23:01:51 - MainThread (14740):
Platform: Windows-10-10.0.19043-SP0
INFO - bookworm.bookworm.bootstrap - 04/03/2022 23:01:51 - MainThread (14740):
OS description: Windows 10 (build 19043), 64-bit edition
INFO - bookworm.bookworm.bootstrap - 04/03/2022 23:01:51 - MainThread (14740):
Application architecture: x86
INFO - bookworm.bookworm.bootstrap - 04/03/2022 23:01:51 - MainThread (14740):
Running a portable copy of Bookworm.
INFO - bookworm.bookworm.bootstrap - 04/03/2022 23:01:51 - MainThread (14740):
Debug mode is off.
DEBUG - bookworm.bookworm.bootstrap - 04/03/2022 23:01:51 - MainThread (14740):
Setting up application subsystems.
DEBUG - bookworm.bookworm.bootstrap - 04/03/2022 23:01:51 - MainThread (14740):
Setting up the configuration subsystem.
DEBUG - bookworm.paths - 04/03/2022 23:01:51 - MainThread (14740):
C:\Users\USR\Downloads\Bookworm-2022.1b1-x86-portable\user-config\config path does not exist, creating...
DEBUG - bookworm.bookworm.bootstrap - 04/03/2022 23:01:51 - MainThread (14740):
Setting up the internationalization subsystem.
DEBUG - bookworm.bookworm.i18n.core - 04/03/2022 23:01:51 - MainThread (14740):
Setting application locale to default.
DEBUG - bookworm.bookworm.i18n.wx_i18n - 04/03/2022 23:01:51 - MainThread (14740):
Setting wx locale to LocaleInfo(identifier="en");language=en.
DEBUG - bookworm.bookworm.bootstrap - 04/03/2022 23:01:51 - MainThread (14740):
Initializing the database subsystem.
INFO - bookworm.bookworm.service.handler - 04/03/2022 23:01:53 - MainThread (14740):
Registering services.
INFO - bookworm.bookworm.service.handler - 04/03/2022 23:01:53 - MainThread (14740):
Registering service: otau.
INFO - bookworm.bookworm.otau - 04/03/2022 23:01:53 - bookworm_threaded_worker_0 (10316):
Checking for updates...
INFO - bookworm.bookworm.service.handler - 04/03/2022 23:01:53 - MainThread (14740):
Registering service: text_to_speech.
INFO - bookworm.bookworm.service.handler - 04/03/2022 23:01:53 - MainThread (14740):
Registering service: annotation.
INFO - bookworm.bookworm.service.handler - 04/03/2022 23:01:53 - MainThread (14740):
Registering service: webservices.
INFO - bookworm.bookworm.service.handler - 04/03/2022 23:01:53 - MainThread (14740):
Registering service: ocr_settings.
INFO - bookworm.bookworm.service.handler - 04/03/2022 23:01:53 - MainThread (14740):
Registering service: ocr.
INFO - bookworm.bookworm.service.handler - 04/03/2022 23:01:53 - MainThread (14740):
Registering service: bookshelf.
INFO - bookworm.bookworm.service.handler - 04/03/2022 23:01:53 - MainThread (14740):
Registering service: cont_reading.
INFO - bookworm.bookworm.service.handler - 04/03/2022 23:01:53 - MainThread (14740):
Registering service: url_open.
INFO - bookworm.bookworm.service.handler - 04/03/2022 23:01:53 - MainThread (14740):
Registering service: wikipedia.
INFO - bookworm.bookworm.service.handler - 04/03/2022 23:01:53 - MainThread (14740):
Registering service: epub_serve.
INFO - bookworm.bookworm.bootstrap - 04/03/2022 23:01:53 - MainThread (14740):
The application has started successfully.
INFO - bookworm.bookworm.bootstrap - 04/03/2022 23:01:53 - MainThread (14740):
Preparing to show the application GUI.
INFO - bookworm.bookworm.otau - 04/03/2022 23:01:54 - bookworm_threaded_worker_0 (10316):
No new version.
INFO - bookworm.bookworm.bootstrap - 04/03/2022 23:01:59 - MainThread (14740):
Shutting down the application.
DEBUG - bookworm.bookworm.concurrency - 04/03/2022 23:01:59 - MainThread (14740):
Canceling  background tasks.
INFO - bookworm.bookworm.bootstrap - 04/03/2022 23:01:59 - MainThread (14740):
The application has exited gracefully.

**Comment by mush42** [comment]
@cary-rowen  @pauliyobo  @MichelSuch 
Does any of you experience this issue?
Please help us with testing this one!

Best
Musharraf

**Comment by mush42** [comment]
@DraganRatkovich  I closed this in error. Sorry!

**Comment by cary-rowen** [comment]
@mush42 
I'd love to help, I tested with the latest build of appveyor, here are the logs, everything looks fine.

```
INFO - bookworm.bookworm.bootstrap - 05/03/2022 08:08:42 - MainThread (14912):
Starting Bookworm.
INFO - bookworm.bookworm.bootstrap - 05/03/2022 08:08:42 - MainThread (14912):
Bookworm Version: 2022.1b1
INFO - bookworm.bookworm.bootstrap - 05/03/2022 08:08:42 - MainThread (14912):
Python version: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:01:48) [MSC v.1929 32 bit (Intel)]
INFO - bookworm.bookworm.bootstrap - 05/03/2022 08:08:42 - MainThread (14912):
Platform: Windows-10-10.0.19044-SP0
INFO - bookworm.bookworm.bootstrap - 05/03/2022 08:08:42 - MainThread (14912):
OS description: Windows 10 (build 19044), 64-bit edition
INFO - bookworm.bookworm.bootstrap - 05/03/2022 08:08:42 - MainThread (14912):
Application architecture: x86
INFO - bookworm.bookworm.bootstrap - 05/03/2022 08:08:42 - MainThread (14912):
Running a portable copy of Bookworm.
INFO - bookworm.bookworm.bootstrap - 05/03/2022 08:08:42 - MainThread (14912):
Debug mode is off.
DEBUG - bookworm.bookworm.bootstrap - 05/03/2022 08:08:42 - MainThread (14912):
Setting up application subsystems.
DEBUG - bookworm.bookworm.bootstrap - 05/03/2022 08:08:42 - MainThread (14912):
Setting up the configuration subsystem.
DEBUG - bookworm.bookworm.bootstrap - 05/03/2022 08:08:42 - MainThread (14912):
Setting up the internationalization subsystem.
DEBUG - bookworm.bookworm.i18n.core - 05/03/2022 08:08:42 - MainThread (14912):
Setting application locale to default.
DEBUG - bookworm.bookworm.i18n.wx_i18n - 05/03/2022 08:08:42 - MainThread (14912):
Setting wx locale to LocaleInfo(identifier="zh_CN");language=zh.
DEBUG - bookworm.bookworm.bootstrap - 05/03/2022 08:08:42 - MainThread (14912):
Initializing the database subsystem.
INFO - bookworm.bookworm.service.handler - 05/03/2022 08:08:42 - MainThread (14912):
Registering services.
INFO - bookworm.bookworm.service.handler - 05/03/2022 08:08:42 - MainThread (14912):
Registering service: otau.
INFO - bookworm.bookworm.service.handler - 05/03/2022 08:08:42 - MainThread (14912):
Registering service: text_to_speech.
INFO - bookworm.bookworm.service.handler - 05/03/2022 08:08:42 - MainThread (14912):
Registering service: annotation.
INFO - bookworm.bookworm.service.handler - 05/03/2022 08:08:42 - MainThread (14912):
Registering service: webservices.
INFO - bookworm.bookworm.service.handler - 05/03/2022 08:08:42 - MainThread (14912):
Registering service: ocr_settings.
INFO - bookworm.bookworm.service.handler - 05/03/2022 08:08:42 - MainThread (14912):
Registering service: ocr.
INFO - bookworm.bookworm.service.handler - 05/03/2022 08:08:42 - MainThread (14912):
Registering service: bookshelf.
INFO - bookworm.bookworm.service.handler - 05/03/2022 08:08:42 - MainThread (14912):
Registering service: cont_reading.
INFO - bookworm.bookworm.service.handler - 05/03/2022 08:08:42 - MainThread (14912):
Registering service: url_open.
INFO - bookworm.bookworm.service.handler - 05/03/2022 08:08:42 - MainThread (14912):
Registering service: wikipedia.
INFO - bookworm.bookworm.service.handler - 05/03/2022 08:08:42 - MainThread (14912):
Registering service: epub_serve.
INFO - bookworm.bookworm.bootstrap - 05/03/2022 08:08:42 - MainThread (14912):
The application has started successfully.
INFO - bookworm.bookworm.bootstrap - 05/03/2022 08:08:42 - MainThread (14912):
Preparing to show the application GUI.
INFO - bookworm.bookworm.bootstrap - 05/03/2022 08:08:47 - MainThread (14912):
Shutting down the application.
DEBUG - bookworm.bookworm.concurrency - 05/03/2022 08:08:47 - MainThread (14912):
Canceling  background tasks.
INFO - bookworm.bookworm.bootstrap - 05/03/2022 08:08:47 - MainThread (14912):
The application has exited gracefully.
```

**Comment by DraganRatkovich** [comment]
Hello,
@mush42 I'm really not sure what could be causing the problem. I've tested the latest made changes downloaded from AppVeyor right now, still the same problem. I use both Win 8.1 and Win 10, but I noticed that on one Windows 10 machine it started without problems, while on another machine, both win 8.1 and 10, the 32-bit version of Bookworm won't start. and each machine set to EN-US locale.

**Comment by DraganRatkovich** [comment]
@cary-rowen What is your locale? I don't really know what could be causing the problem. My locale, as I said, is set to en-us.

**Comment by cary-rowen** [comment]
@DraganRatkovich 
Hello, my locale is Simplified Chinese

**Comment by DraganRatkovich** [comment]
@mush42 I tried changing my locale to en-gb, thought that might fix the error, but no, the same error still occurs. Also, tried to change to En-US my region, date and time formats, but still the same error. What should I do in this case? Why is only the 32-bit version affected and why does the log show an en-GB error? Still can't figure out why the 64-bit version works very well.

**Comment by mush42** [comment]
Hello @DraganRatkovich 

I'm sorry that you still face this issue. I understand it is very frustrating.

Would you mind checking the configuration file. For portable copies of Bookworm it should be in portable_directory\user-config\config\bookworm.ini

Open that file in notepad or notepad++, and change the language entry from default (or whatever it is) to en. If it is not default though, set it to default.

Best
Musharraf

**Comment by DraganRatkovich** [comment]
@mush42 The .ini file, in both 32-bit and 64-bit configurations, has the same value in the language, so there is no need to change it, I checked it right now. I also changed the default to en but nothing changed, the same issue still exists.

**Comment by DraganRatkovich** [comment]
@mush42 Also, even I change the value to en or something else, after running the program, it automatically returns the default value for the language section.

**Comment by mush42** [comment]
@DraganRatkovich 

I have to check what does wxpython do with the locale. I hear it changes it randomly.

I'll check and get back to you

Best
Musharraf

**Comment by DraganRatkovich** [comment]
@mush42 Okay, waiting for your information.

**Comment by mush42** [comment]
@DraganRatkovich 

I pushed a tentative fix, please check if that fixes your problem.

Best
Musharraf

**Comment by DraganRatkovich** [comment]
Hello @mush42
Thanks, this has been fixed, it works really well now, and the 32bit tts voice that is installed works amazing as well.

**Comment by mush42** [comment]
@DraganRatkovich 
I am glad to hear that.

Best
Musharraf

**Comment by cary-rowen** [comment]
Hi,
congratulations on fixing this bug
